<!DOCTYPE html>

<html>
<head>
<meta charset="UTF-8">

<title>module RSpec::Core::MultipleExceptionError::InterfaceTag - RDoc Documentation</title>

<script type="text/javascript">
  var rdoc_rel_prefix = "../../../";
  var index_rel_prefix = "../../../";
</script>

<script src="../../../js/jquery.js"></script>
<script src="../../../js/darkfish.js"></script>

<link href="../../../css/fonts.css" rel="stylesheet">
<link href="../../../css/rdoc.css" rel="stylesheet">



<body id="top" role="document" class="module">
<nav role="navigation">
  <div id="project-navigation">
    <div id="home-section" role="region" title="Quick navigation" class="nav-section">
  <h2>
    <a href="../../../index.html" rel="home">Home</a>
  </h2>

  <div id="table-of-contents-navigation">
    <a href="../../../table_of_contents.html#pages">Pages</a>
    <a href="../../../table_of_contents.html#classes">Classes</a>
    <a href="../../../table_of_contents.html#methods">Methods</a>
  </div>
</div>

    <div id="search-section" role="search" class="project-section initially-hidden">
  <form action="#" method="get" accept-charset="utf-8">
    <div id="search-field-wrapper">
      <input id="search-field" role="combobox" aria-label="Search"
             aria-autocomplete="list" aria-controls="search-results"
             type="text" name="search" placeholder="Search" spellcheck="false"
             title="Type to search, Up and Down to navigate, Enter to load">
    </div>

    <ul id="search-results" aria-label="Search Results"
        aria-busy="false" aria-expanded="false"
        aria-atomic="false" class="initially-hidden"></ul>
  </form>
</div>

  </div>

  

  <div id="class-metadata">
    
    
    
    
    <!-- Method Quickref -->
<div id="method-list-section" class="nav-section">
  <h3>Methods</h3>

  <ul class="link-list" role="directory">
    
    <li ><a href="#method-c-for">::for</a>
    
    <li ><a href="#method-i-add">#add</a>
    
  </ul>
</div>

  </div>
</nav>

<main role="main" aria-labelledby="module-RSpec::Core::MultipleExceptionError::InterfaceTag">
  <h1 id="module-RSpec::Core::MultipleExceptionError::InterfaceTag" class="module">
    module RSpec::Core::MultipleExceptionError::InterfaceTag
  </h1>

  <section class="description">
    
<p>@private Used so there is a common module in the ancestor chain of this
class and `RSpec::Expectations::MultipleExpectationsNotMetError`, which
allows code to detect exceptions that are instances of either, without
first checking to see if rspec-expectations is loaded.</p>

  </section>

  
  
  
  <section id="5Buntitled-5D" class="documentation-section">
    

    

    

    

    
     <section id="public-class-5Buntitled-5D-method-details" class="method-section">
       <header>
         <h3>Public Class Methods</h3>
       </header>

    
      <div id="method-c-for" class="method-detail ">
        
        <div class="method-heading">
          <span class="method-name">for</span><span
            class="method-args">(ex)</span>
          
          <span class="method-click-advice">click to toggle source</span>
          
        </div>
        

        <div class="method-description">
          
          <p>Provides a way to force `ex` to be something that satisfies the multiple
exception error interface. If it already satisfies it, it will be returned;
otherwise it will wrap it in a `MultipleExceptionError`. @private</p>
          
          

          
          <div class="method-source-code" id="for-source">
            <pre><span class="ruby-comment"># File vendor/bundle/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb, line 437</span>
<span class="ruby-keyword">def</span> <span class="ruby-keyword">self</span>.<span class="ruby-keyword">for</span>(<span class="ruby-identifier">ex</span>)
  <span class="ruby-keyword">return</span> <span class="ruby-identifier">ex</span> <span class="ruby-keyword">if</span> <span class="ruby-keyword">self</span> <span class="ruby-operator">===</span> <span class="ruby-identifier">ex</span>
  <span class="ruby-constant">MultipleExceptionError</span>.<span class="ruby-identifier">new</span>(<span class="ruby-identifier">ex</span>)
<span class="ruby-keyword">end</span></pre>
          </div>
          
        </div>

        

        
      </div>

    
    </section>
  
     <section id="public-instance-5Buntitled-5D-method-details" class="method-section">
       <header>
         <h3>Public Instance Methods</h3>
       </header>

    
      <div id="method-i-add" class="method-detail ">
        
        <div class="method-heading">
          <span class="method-name">add</span><span
            class="method-args">(exception)</span>
          
          <span class="method-click-advice">click to toggle source</span>
          
        </div>
        

        <div class="method-description">
          
          <p>Appends the provided exception to the list. @param exception [Exception] <a
href="../../../Exception.html">Exception</a> to append to the list.
@private</p>
          
          

          
          <div class="method-source-code" id="add-source">
            <pre><span class="ruby-comment"># File vendor/bundle/ruby/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/exception_presenter.rb, line 411</span>
<span class="ruby-keyword">def</span> <span class="ruby-identifier">add</span>(<span class="ruby-identifier">exception</span>)
  <span class="ruby-comment"># `PendingExampleFixedError` can be assigned to an example that initially has no</span>
  <span class="ruby-comment"># failures, but when the `aggregate_failures` around hook completes, it notifies of</span>
  <span class="ruby-comment"># a failure. If we do not ignore `PendingExampleFixedError` it would be surfaced to</span>
  <span class="ruby-comment"># the user as part of a multiple exception error, which is undesirable. While it&#39;s</span>
  <span class="ruby-comment"># pretty weird we handle this here, it&#39;s the best solution I&#39;ve been able to come</span>
  <span class="ruby-comment"># up with, and `PendingExampleFixedError` always represents the _lack_ of any exception</span>
  <span class="ruby-comment"># so clearly when we are transitioning to a `MultipleExceptionError`, it makes sense to</span>
  <span class="ruby-comment"># ignore it.</span>
  <span class="ruby-keyword">return</span> <span class="ruby-keyword">if</span> <span class="ruby-constant">Pending</span><span class="ruby-operator">::</span><span class="ruby-constant">PendingExampleFixedError</span> <span class="ruby-operator">===</span> <span class="ruby-identifier">exception</span>

  <span class="ruby-keyword">return</span> <span class="ruby-keyword">if</span> <span class="ruby-identifier">exception</span> <span class="ruby-operator">==</span> <span class="ruby-keyword">self</span>

  <span class="ruby-identifier">all_exceptions</span> <span class="ruby-operator">&lt;&lt;</span> <span class="ruby-identifier">exception</span>

  <span class="ruby-keyword">if</span> <span class="ruby-identifier">exception</span>.<span class="ruby-identifier">class</span>.<span class="ruby-identifier">name</span> <span class="ruby-operator">=~</span> <span class="ruby-regexp">/RSpec/</span>
    <span class="ruby-identifier">failures</span> <span class="ruby-operator">&lt;&lt;</span> <span class="ruby-identifier">exception</span>
  <span class="ruby-keyword">else</span>
    <span class="ruby-identifier">other_errors</span> <span class="ruby-operator">&lt;&lt;</span> <span class="ruby-identifier">exception</span>
  <span class="ruby-keyword">end</span>
<span class="ruby-keyword">end</span></pre>
          </div>
          
        </div>

        

        
      </div>

    
    </section>
  
  </section>
</main>


<footer id="validator-badges" role="contentinfo">
  <p><a href="http://validator.w3.org/check/referer">Validate</a>
  <p>Generated by <a href="https://rdoc.github.io/rdoc">RDoc</a> 5.0.0.
  <p>Based on <a href="http://deveiate.org/projects/Darkfish-RDoc/">Darkfish</a> by <a href="http://deveiate.org">Michael Granger</a>.
</footer>

